name: CI

on: 
  push:
    branches:
      - master
    paths-ignore:
      - 'frontend/**'
      - 'backend/.gitignore'
      - 'backend/Procfile'
      - 'backend/**.md'
      - 'backend/**.txt'
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'frontend/**'
      - 'backend/.gitignore'
      - 'backend/Procfile'
      - 'backend/**.md'
      - 'backend/**.txt'
      - '**.md'

env:
  DB_URL: ${{secrets.DB_URL}}
  EMAIL_ADDRESS: ${{secrets.EMAIL_ADDRESS}}
  EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
  SECRET_KEY: ${{secrets.SECRET_KEY}}
  TEST_DB_URL: ${{secrets.TEST_DB_URL}}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./backend/requirements-dev.txt
        pip install -r ./backend/requirements.txt
        
    - name: Test with pytest
      working-directory: ./backend
      run: |
        python -m pytest
        
    - name: Analysing the code with pylint
      working-directory: ./backend
      run: |
        pylint ../backend
